timols/java-gitlab-api

src/main/java/org/gitlab/api/GitlabAPI.java

instead of retrieving all merge request and filtering them client side. This will only fetch the open from gitlab server.
This will speedup especially old projects with lots of closed merge requests.

Changed getOpenMergeRequests to only retrieve the open merge requests 

---

src/main/java/org/gitlab/api/GitlabAPI.java

getMergeRequests was only returning merge request from first page of gitlab API, this makes it return all results. Also added a getOpenMergeRequests overload to work with just projectId.

Make getMergeRequests pull all merge requests

---

src/main/java/org/gitlab/api/GitlabAPI.java

This fixes a crash in the `deleteProject` method. The stack trace I received for the (fixed) crash is below.
```
org.codehaus.jackson.map.JsonMappingException: Can not instantiate value of type [simple type, class java.lang.Void] from JSON boolean value; no single-boolean/Boolean-arg constructor/factory method
at org.codehaus.jackson.map.deser.std.StdValueInstantiator.createFromBoolean(StdValueInstantiator.java:328)
at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromBoolean(BeanDeserializer.java:855)
at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:594)
at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2732)
at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1863)
at …
```

Fix crash when deleting a project

---

pom.xml
src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabAbstractMember.java
src/main/java/org/gitlab/api/models/GitlabAccessLevel.java
src/main/java/org/gitlab/api/models/GitlabBranch.java
src/main/java/org/gitlab/api/models/GitlabBranchCommit.java
src/main/java/org/gitlab/api/models/GitlabCommit.java
src/main/java/org/gitlab/api/models/GitlabCommitDiff.java
src/main/java/org/gitlab/api/models/GitlabGroup.java
src/main/java/org/gitlab/api/models/GitlabIssue.java
src/main/java/org/gitlab/api/models/GitlabMergeRequest.java
src/main/java/org/gitlab/api/models/GitlabMilestone.java
src/main/java/org/gitlab/api/models/GitlabNamespace.java
src/main/java/org/gitlab/api/models/GitlabNote.java
src/main/java/org/gitlab/api/models/GitlabPermission.java
src/main/java/org/gitlab/api/models/GitlabProject.java
src/main/java/org/gitlab/api/models/GitlabProjectAccessLevel.java
src/main/java/org/gitlab/api/models/GitlabProjectHook.java
src/main/java/org/gitlab/api/models/GitlabSSHKey.java
src/main/java/org/gitlab/api/models/GitlabSession.java
src/main/java/org/gitlab/api/models/GitlabUser.java

Upgraded the Jackson dependencies from Codehouse libs to Fasterxml as when using the API with some projects which already have fasterxml.jackson on the classpath, the jackson dependencies are duplicated. Still this is no problem as the packages are not the same, but it is always nice to have a clean classpath. So may be you can have 2 versions of API one with Codehouse Jackson (1.1.x) and one with the Fasterxml Jackson (1.2.x).

Dependency Upgrades

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabSSHKey.java

API function was introduced by PR: https://github.com/gitlabhq/gitlabhq/pull/9591
Get SSH key with user by ID of an SSH key. Note only administrators can lookup SSH key with user by ID of an SSH key.
```
GET /keys/:id
```
Parameters:
- `id` (required) - The ID of an SSH key
```json
{
"id": 1,
"title": "Sample key 25",
"key": "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAiPWx6WM4lhHNedGfBpPJNPpZ7yKu+dnn1SJejgt1256k6YjzGGphH2TUxwKzxcKDKKezwkpfnxPkSMkuEspGRt/aZZ9wa++Oi7Qkr8prgHc4soW6NUlfDzpvZK2H5E7eQaSeP3SAwGmQKUFHCddNaP0L+hM7zhFNzjFvpaMgJw0=",
"created_at": "2015-09-03T07:24:44.627Z",
"user": {
"name": "John Smith",
"username": "john_smith",
"id": 25,
"state": "active",
"avatar_url": "http://www.gravatar.com/avatar/cfa35b8cd2ec278026357769582fa563?s=40\u0026d=identicon",
"web_url": …
```

Add API method for get SSH key with user information by ID of an SSH key: getSSHKey

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/TokenType.java
src/test/java/org/gitlab/api/http/GitlabHTTPRequestorTest.java

For OAuth the uri query parameter should be named access_token instead of
private_token. To support both a enum TokenType is introduced and should
be used to select which token type to be used for the API access.
For backwards compatibility TokenType#PRIVATE_TOKEN will be used by
default.
Signed-off-by: Andreas Häber <andreas.haber@intele.com>

Support OAuth access_token

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabCommitStatus.java

Add the new commit status API methods that will be introduced in 8.1.
[Documentation](http://doc.gitlab.com/ce/api/commits.html#get-the-status-of-a-commit)
Note there is [currently a bug](https://gitlab.com/gitlab-org/gitlab-ce/issues/3080) with the `GET` API which will return `404` if there are no statuses for a given commit. In 8.1 this will instead return an empty array.

Add methods for the new commit status API

---

src/test/java/org/gitlab/api/GitlabAPITest.java

JUnit ignores GitlabAPIT because of wrong naming. Fixes naming issue.

Correct name of GitlabAPI Test

---

src/main/java/org/gitlab/api/GitlabAPI.java

Implements the following Gitlab API Call: http://doc.gitlab.com/ce/api/notes.html#get-single-merge-request-note

Add Method to get a single Merge Request Note

---

src/main/java/org/gitlab/api/GitlabAPI.java

Implements a convenient method to retrieve a Merge Request using its iid instead of id.
It uses the remote Gitlab API call to list Merge Request while providing the iid filter. The call returns a list of zero or one items.
- If result is non zero, return the first result
- If result is zero, throw a FileNotFoundException. This mimics the behavior of other API calls.

Add Method to return Merge Request by iid

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabMergeRequest.java

Implements Gitlab API call to get Merge Request Changes: http://doc.gitlab.com/ce/api/merge_requests.html#get-single-mr-changes
Note that in the documentation the JSON Parameter Name is 'files' which is wrong. In fact the Gitlab API uses the JSON Parameter Name 'changes'.

Add method to retrieve merge request changes

---

src/main/java/org/gitlab/api/AuthMethod.java
src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/TokenType.java
src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java
src/test/java/org/gitlab/api/GitlabAPITest.java

Fixes #79.
This PR introduced a new authentication method using HTTP Headers.
As we now have 2 different method to authenticate, the constructer of GitlabAPI includes another parameter AuthMethod which is a simple enum.
TokenType was extended with information needed for authentication like Header name and Header format.
The authentication was moved from GitlabAPI to GitlabHTTPRequestor.
Authentication information is passed using a fluent interface:
`return new GitlabHTTPRequestor(this).authenticate(apiToken, tokenType, authMethod).method("POST");`
Tested both using private tokens and access token.
The PR includes only minor compatibility changes:
- getAPIUrl doesn't return the private token anymore.
- Exceptions thrown doesn't include the private token anymore.
This PR sets the HEADER …

Implement Authentication via an HTTP Header 

---

src/main/java/org/gitlab/api/GitlabAPIException.java
src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java
src/test/java/org/gitlab/api/GitlabAPITest.java

Current implementation includes no way of handling the returned http error codes. This PR introduces a GitlabAPIException class which extends from IOException but includes the error code. The changes are 100% backwards compatible.
This is probably the last one of my series of PRs for now :-)

Expose HTTP Code through GitlabAPIException

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabMilestone.java

Wraps "POST" and "PUT" verbs for creating and updating milestones in api version 3.
* src/main/java/org/gitlab/api/GitlabAPI.java
* Added overloaded createMilestone methods
* Added overloaded updateMilestone methods
*  src/main/java/org/gitlab/api/models/GitlabMilestone.java
* Added JsonProperty for proper deserialization of project ID.  In my testing I was attempting to create a new milestone and update it on the next line of code.  The update was failing because the project ID was zero.  This seemed like the best way to solve the problem, but it can be solved other ways if need be.
I may have overlooked them, but I didn't see contribution guidelines.  I did test this code, but didn't use the GitlabAPITest :)  I'm also not sure if there are certain kinds of changes you're accepting right …

Adds create / edit support for milestones

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabLabel.java

Wraps "POST", "GET", "PUT" and "DELETE" HTTP verbs for api version 3.
* src/main/java/org/gitlab/api/GitlabAPI.java
* Added overloaded methods to get labels by project.
* Added overloaded methods to create new labels.
* Added overloaded methods to delete an existing label
* Added a single method to update an existing label
*  src/main/java/org/gitlab/api/models/GitlabLabel.java
* Created a new type which models a Gitlab label.
If you're interested in this PR and would like any changes, please do let me know and I'll be happy to oblige.

Adds CRUD support for labels

---

src/main/java/org/gitlab/api/GitlabAPI.java

Corrects an issue in which GitlabAPI.findUsers returns the first default
page of users when the emailOrUsername argument is null or empty.

Resolves #93: Fixes pagination issues with find users

---

src/main/java/org/gitlab/api/GitlabAPI.java

From http://doc.gitlab.com/ce/api/projects.html#create-project-for-user I've added the import_url param, which was already exposed in `createProject()`, but not in `createUserProject()`.

Added import_url param to createUserProject

---

src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java
src/main/java/org/gitlab/api/models/GitlabSession.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1161 - @Override annotation should be used on any method overriding (since Java 5) or implementing (since Java 6) another one”. You can find more information about the issue here: https://dev.eclipse.org/sonar/rules/show/squid:S1161.
Please let me know if you have any questions.
Christian

Code Quality Improvement - @Override annotation should be used on any method overriding (since Java 5) or implementing (since Java 6) another one

---

src/main/java/org/gitlab/api/GitlabAPI.java

So that GitLab can link the comment to the specified line of the specified path...

post 'line_type' parameter to gitlab when creating a commit comment

---

.gitignore
build.gradle

I wanted to use this library, so I wanted to get started by looking at the source code. I noticed that the gradle IDE plugins were not included in the build file. Since there's almost no overhead having the plugins included in the build script and makes it easier for anyone to get started by generating the IDE files from command line, I've added it.

[Enhancement] Add IDE plugins to build file

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java

See [the API docs for the method](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/builds.md#get-build-artifacts)
I ran into an odd issue where the download files were 10MB too big
and were in an invalid .tgz format, but reading the byte stream
from the actual input stream instead of the reader fixed the issue.
I don't know if it was broken from #69 or if it's a change in gitlab?

Added getBuildsArtifact method

---

src/main/java/org/gitlab/api/models/GitlabGroup.java
src/test/java/org/gitlab/api/models/GitlabGroupTest.java

This resolves a NullPointerException that was encountered when unmarshalling a a GitlabGroup JSON object with a null ldap_access attribute.
Fixes #117

Added a null check to GitlabGroup#setLdapAccess. 

---

src/main/java/org/gitlab/api/GitlabAPI.java

The default branch controls which branch is displayed when a
user navigates to a project in Gitlab.  Typically Gitlab will
default to the first branch that is pushed to the repository.
In cases where automation is used to create other branches
prior to creating the master or development branches, it may
be necessary to use this "default_branch" field to specify
the default branch that should be displayed to users.

Adding a default branch argument to the updateProject method.

---

src/main/java/org/gitlab/api/GitlabAPI.java

There is currently no way to list all project members if there are more than 20. This pr adds support for pagination for the getProjectMembers call

Support for listing more than 20 project members

---

src/main/java/org/gitlab/api/models/GitlabUser.java

I would like the `last_sign_in_at` and `current_sign_in_at` properties to be added to the GitlabUser object.

Add "last_sign_in_at" and "current_sign_in_at" properties to GitlabUser

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/test/java/org/gitlab/api/GitlabAPITest.java

Add get group by path.
According to the [API Documentation](http://docs.gitlab.com/ce/api/groups.html#details-of-a-group) the parameter ``id`` of the endpoint ``GET /groups/:id`` can be ``The ID or path of a group``.

Add get group by path

---

src/main/java/org/gitlab/api/GitlabAPI.java

Separate pull request for marking them deprecated incase you agree. Should merge in fine before or after the other one I tested it locally.

Deprecating the parameter versions of the createProject, updateProject and createUserProject calls

---

src/main/java/org/gitlab/api/models/GitlabUser.java
src/main/java/org/gitlab/api/models/GitlabUserIdentity.java

This pull request will add the identities-property as a List. Currently the library would return the provider and extern_uid directly from the user object. These are always empty and this is the solution because the keys are in the list of identities.
See: https://docs.gitlab.com/ce/api/users.html#for-admin

Add List of identities under GitlabUser

---

src/main/java/org/gitlab/api/models/GitlabGroup.java
src/main/java/org/gitlab/api/models/GitlabProject.java
src/main/java/org/gitlab/api/models/GitlabProjectSharedGroup.java

This merge request adds support to list all projects that are shared with a group to the `GitlabGroup` object. This is accessible with `GitlabGroup.getSharedProjects()`.
Also, created a new `GitlabProjectSharedGroup` class to represent the relationship of a project being shared with a group since the [API exposes limited information](https://docs.gitlab.com/ee/api/projects.html#get-single-project) about the group in the project's `shared_with_groups` property. This is accessible with `GitlabProject.getSharedWithGroups()`. If someone wants more information about the group, then they'll have to use `GitlabAPI.getGroup()` to get the details of that group.

Add support for projects shared with a group.

---

src/main/java/org/gitlab/api/GitlabAPI.java

Until now, the `GitlabAPI#getGroupProjects()`list only the first 20 projects in a group.
-----
```java
final GitlabGroup group = gitlabAPI.getGroup(".....");
final String tailUrl = GitlabGroup.URL + "/" + group.getId() + GitlabProject.URL;
final List<GitlabProject> projects = gitlabAPI.retrieve().getAll(tailUrl, GitlabProject[].class);
```

GitlabAPI#getGroupProjects() retrieve all projects from the group

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/Pagination.java
src/test/java/org/gitlab/api/PaginationTest.java

Motivation:
Speed up API calls.
Modifications:
Set maximum per page param when retrieving all results.
Result:
Less calls to GitLab API endpoint when retrieving all results.
Fixes https://github.com/timols/java-gitlab-api/issues/162.

API calls retrieving all results may be slow

---

src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java
src/test/java/org/gitlab/api/GitlabAPITest.java

Fixes https://github.com/timols/java-gitlab-api/issues/202
Simplest solution is to not attempt to map to the Void class that appears to be passed in for all of the DELETE based operations.
Additionally, I fixed a minor typo in the GitlabAPITest class.

Handle 204 response

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/CreateGroupRequest.java
src/main/java/org/gitlab/api/models/GitlabGroup.java

... and every other group creation option that is presently documented.
I decided not to add more parameters to the existing methods, because they were getting unwieldy. 
I've manually tested this on our Gitlab 9.0.x instance and it appears to work.

Support creation of subgroups

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabMergeRequest.java

Hello,
I just submit some improvements in the GitlabAPI interface:
- new methods `getMergedMergeRequests`
- new methods `getClosedMergeRequests`
- new methods `getMergeRequestWithStatus`
- new methods `cherryPick`
- handling `Pagination` on MergeRequest methods
- removed pagination limit in `getAllMergeRequests`
- minor refactorisation of `getMergeRequests` methods
Let me know if this is valuable enough to be merged :-)
Best regards,
Cédric

Improvement of getMergedRequest methods and new cherryPick method

---

src/main/java/org/gitlab/api/GitlabAPI.java

It looks like the v4 API started to paginate endpoints that return arrays/lists of items. I found `getRepositoryTree()`, `getBranches()`, and `getTags()` needed updating for sure. I'm not sure about others, I just confirmed these three.

RepositoryTree, Branches, and Tags lists are paginated in the v4 api.

---

src/main/java/org/gitlab/api/GitlabAPI.java

Looks like one property change with the v4 API was missed.

request_enabled property on projects changed to request_access_enabled

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/CreateGroupRequest.java
src/main/java/org/gitlab/api/models/GitlabVisibility.java

Fixes for issues I had with createGroup.
**getGroup(String)** updated to support seeking subgroups, and **createGroup(createGroupRequest, GitlabUser)** properly allows group visibility to be set.

Fix for Setting a new Group's Visibility

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabMilestone.java

PR for issue #226 
P.S.: Should the order of `dueDate` and `startDate` input arguments for `createMilestone` and `updateMilestone` be reversed or the current order is fine?

Milestones API: Add start_date field

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabMilestone.java

Minus some trailing whitespace removed, this PR adds methods to the `GitlabAPI` class to:
* retrieve group milestones
* retrieve group milestone issues
* retrieve project milestone issues
API Reference - https://docs.gitlab.com/ee/api/group_milestones.html

Retrieve group milestones

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/test/java/org/gitlab/api/GitlabAPIIT.java

This PR first fixes two methods to retrieve owned and starred projects, then adds a new method to retrieve projects that the user is member of. It also adds a test for it.
API Reference - https://docs.gitlab.com/ee/api/projects.html#list-projects
The problem with the fixed methods was that two query objects were being used in the generation of the same url, rendering it like this `/projects?owned=true?page=100` (note `?` twice). This was fixed by merging the two query objects before and using the resulting query object in the generation of the url.

Add method to retrieve projects that the user is member of

---

src/main/java/org/gitlab/api/GitlabAPI.java

The previous version sent merge_requests?iid=17, but the API ignores that parameter.  merge_requests/17 is correct.

Fix getMergeRequestByIid

---

src/main/java/org/gitlab/api/GitlabAPI.java

make getProject take unescaped group id, like getGroup

---

src/main/java/org/gitlab/api/GitlabAPI.java

Make the getMergeRequestApprovals API consistent with notes api by
looking at the projectId field instead of the targetProjectId field.
For projects which are sourced from upstream, I believe that these
will be the same (from reading the gitlab code -- the API docs are
unclear; see https://gitlab.com/gitlab-org/gitlab-ce/issues/38539 ).

getMergeRequestApprovals: use projectId not targetProjectId

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabIssueTimeStats.java

This PR adds a method to the `GitlabAPI` class to retrieve the time stats from an issue.
API reference - https://docs.gitlab.com/ee/api/issues.html#get-time-tracking-stats

Add method and respective model to retrieve issue time stats

---

src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java

https://gitlab.com/gitlab-org/gitlab-ce/issues/759 is closed
gitlab repo id = 13083
https://gitlab.com/api/v4/projects/13083/repository/commits?page=1 
\=\=
https://gitlab.com/api/v4/projects/13083/repository/commits
```bash
diff <(curl -s https://gitlab.com/api/v4/projects/13083/repository/commits) <(curl -s 'https://gitlab.com/api/v4/projects/13083/repository/commits?page=1' )
```
close #237

Remove conditional processing for commits

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java
src/test/java/org/gitlab/api/GitlabJson.java
src/test/java/org/gitlab/api/http/GitlabHTTPRequestorTest.java

This is a small change to allow the API to pull the project JSON directly from gitlab without parsing it.   One small change to the original code is that I renamed 'data' in GitlabHTTPRequestor.java to json not to override the field 'data' defined in the class.

Added getProjectJson() methods

---

src/main/java/org/gitlab/api/models/GitlabGroup.java

Noticed there was some missing metadata for a available in the json response that was not in the current version of the GitlabGroup model object.

Add additional data to the GitlabGroup model object

---

src/main/java/org/gitlab/api/models/GitlabSimpleRepositoryFile.java

Hello,
In the new v4 file repository services in GitLab 10.2.3-ee I see that the field file_name is actually called file_path, despite what is in the official GitLab documentation.  For example, /api/v4/projects/:id/repository/files/:file_path actual response looks like:
{
"file_path": "example.txt",
"branch": "master"
}
I think that this is also the case in the ce edition, please correct me if I'm wrong.
Thank you for maintaining this project.

Rename file_name to file_path

---

build.gradle
src/main/java/org/gitlab/api/GitlabAPI.java
src/test/java/org/gitlab/api/GitlabAPIIT.java

Changed: 
- Put back API getAllProjects() 
- fixed JUnit for getAllProjects() 
- On a vanilla system since the order of tests cannot be guaranteed some of the count tests fail.  Changed the Junit to simply check for exception rather than actual project numbers.
- Changed the next version to 1.2.9-SNAPSHOT (1.2.8 is on maven)

This is a partial revert of a previous commit, fixed two JUnits that fail on a "vanila" docker gitlab install

---

src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java

This should make it so that consumers can catch an Exception instead of any Error type.

gh-275: Propagate exceptions as a RuntimeException instead of java.lang.Error

---

src/main/java/org/gitlab/api/GitlabAPI.java

- Add method to update an existing Gitlab Member's Access Level.
- Allow for user to specify expiration date for Gitlab Member Access Level.

GitLabProjectMember Permission Level

---

LICENSE
NOTICE
build.gradle
pom.xml

Followed the advice from Apache as stated in #285 
- Renamed previous LICENSE file to NOTICE
- Added Apache License 2.0 text as LICENSE file to root directory
- Adjusted gradle and maven build to add both NOTICE and LICENSE file into root of binary and sources jars

Improved Apache 2.0 licensing Information

---

src/main/java/org/gitlab/api/GitlabAPI.java

- Fixed both methods to extract correct IID rather than the ID to access
the Notes from an GitlabIssue

GitlabAPI.getNotes(...) call creating non api v4 compliant URL (#283)

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabRunner.java

- Allow for controlled pagination of Projects and Runners API
- Add new Runners API fields `online` and `status`

Controlled Pagination for Gitlab Projects and Runners

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabProject.java
src/test/java/org/gitlab/api/GitlabAPIIT.java

Fixing that namespace is not sending during project fork

Sending namespace during fork

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/models/GitlabDiscussion.java

This pull request implements the discusion API for merge requests.
The java API is extended with the functionality to:
- create a discussion
- add notes to a discussion
- delete notes from a discussion
- resolve a discussion
- modify a discussion

Merge request discussion API implementation.

---

src/main/java/org/gitlab/api/GitlabAPI.java

The merge request API uses the mergeRequestIid, but the arguments are called mergeRequestId. This pr renames all mergeRequestId arguments to mergeRequestIid.
This pull request also fixes #299

Rename wrong mergeRequestId arguments to mergeRequestIid.

---

src/main/java/org/gitlab/api/GitlabAPI.java

This PR add a method to get single tag from gitlab. The corresponding api spec can be found here: https://docs.gitlab.com/ee/api/projects.html#get-single-project

Add api to fetch single tag

---

src/main/java/org/gitlab/api/models/GitlabMergeRequest.java

Some getters are returning primitive values instead of the declared Object types, causing problems with serialization and npe.

adjusting getters return type

---

src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java

In issue #337 we discussed rethrowing the IOException from the API border, but since many methods nowadays don't `throws IOException` it would be a huge breaking change.
I therefore decided to only change the exception type from RuntimeException to UncheckedIOException to be able to distinguish between them in API consuming business logic. For consumers already catching RuntimeException to handle the wrapped IOException, nothing will change.

Throw UncheckedIOException instead of generic RuntimeException

---

src/main/java/org/gitlab/api/models/GitlabMergeRequest.java

Fix the type of changesCount in the GitlabMergeRequest Model
GitlabApi official website:
https://docs.gitlab.com/ee/api/merge_requests.html#create-mr
Sometimes the '+' will appear
I update the type to string

update GitlabMergeRequest prop changesCount to string

---

src/main/java/org/gitlab/api/GitlabAPI.java

Hi,
In the `GitLabAPI.getCommits(projectId, pagination, branchOrTag), the pagination argument is ignored when invoking the extended `getCommit` method. Since there is no warning about that, not all the commits will come back.
A temporary fix in 4.0.1 is to directly call `getCommits(projectId, pagination, branchOrTag, null)`.
Best regards !
Cédric

Fix commits pagination

---

src/main/java/org/gitlab/api/GitlabAPI.java

- Encode '+' characters in paths with '%20'

Files containing spaces in their path are wrongly encoded (#331)

---

src/main/java/org/gitlab/api/jackson/InstantDeserializer.java
src/main/java/org/gitlab/api/models/GitlabPipeline.java
src/test/java/org/gitlab/api/InstantDeserializerTest.java

Add missing fields to class GitlabPipeline.

Add missing fields to GitlabPipeline

---

src/main/java/org/gitlab/api/GitlabAPI.java

Added optionally params (path and name) for fork project [GitLab doc fork-project](https://docs.gitlab.com/ee/api/projects.html#fork-project)

Added params 'path' and 'name' for create fork

---

src/main/java/org/gitlab/api/GitlabAPI.java
src/main/java/org/gitlab/api/Pagination.java
src/main/java/org/gitlab/api/query/PaginationQuery.java
src/main/java/org/gitlab/api/query/PipelinesQuery.java
src/main/java/org/gitlab/api/query/ProjectsQuery.java

The gitlab api provides numerous parameters. Most are currently not offered by java-gitlab-api.
The current design provides API parameters individually as method parameters. This is not very future proof and clumsy.
Instead, one could directly accept a query object. In order to get at least a certain abstraction, one simply derives sub-classes for the respective use cases.
Because I did not "hide" the query (as implemented in the old pagination class), it is also possible to add parameters that may be added to the API in the future. This would basically make the methods forward-compatible.
I made the whole example of the `GitlabAPI#getProjects()` ([GitlabAPI](https://github.com/tristanlins/java-gitlab-api/blob/feature-specialized-queries/src/main/java/org/gitlab/api/GitlabAPI.java#L834-L84 …

Proposal, use specialized query objects instead of parameters

---

src/main/java/org/gitlab/api/models/GitlabIssue.java

This PR was proposed to fix the issue of due_date parse issue.
https://github.com/timols/java-gitlab-api/issues/350

use Date to parse due_date for GitlabIssue like GitlabMilestone

---

.travis.yml
src/main/java/org/gitlab/api/GitlabAPI.java
src/test/java/org/gitlab/api/GitlabAPIUT.java
src/test/java/org/gitlab/api/InstantDeserializerTest.java

closes #259
Tests passed locally:
```
$ mvn -Pdocker-gitlab clean verify
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.gitlab.api.GitlabUploadIT
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 1.088 s - in org.gitlab.api.GitlabUploadIT
[INFO] Running org.gitlab.api.GitlabAPIIT
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in org.gitlab.api.GitlabAPIIT
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 2
[INFO] 
[INFO] 
[INFO] --- docker-maven-plugin:0.23.0:stop (default-stop) @ java-gitlab-api ---
[INFO] DOCKER> [gitlab/gitlab-ce:latest] "gitlab": Stop and removed container …
```

Get commits for merge request

---

src/main/java/org/gitlab/api/GitlabAPI.java

Change little bit, makes hooks api support pagination. Before this it max return 20 item.

hooks api support pagination
