src/main/java/org/gitlab/api/GitlabAPI.java
Added a function to accept a merge request by the api.
=> Accept a merge request

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabSSHKey.java
I added 3 API calls to get/create/delete ssh keys. I also added the corresponding ssh key model.
=> adding user ssh key api calls and ssh key model

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabUser.java
- block/unblock user
- update project
- transfer project to a new namespace
=> Added various API calls:

src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java
Hi Tim,
I took a look at #59. As the connection is not reused, we can disconnect it right away, no need to change the GitlabAPI API.
It would be nice if we could get a release on Central once this change is merged!
Thanks for your work. Greatly appreciated!
-- 
Guillaume
=> Disconnect the HTTPURLConnection after use (Fixes #59).

src/main/java/org/gitlab/api/GitlabAPI.java
Hi Tim,
We needed it to deploy keys automatically so here it is!
Thanks!
=> Add support for project deploy keys

src/main/java/org/gitlab/api/GitlabAPI.java
Hi Tim,
A small fix for what I've pushed yesterday.
=> skip_confirmation should be null safe

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java, src/main/java/org/gitlab/api/models/GitlabRepositoryTree.java, src/test/java/org/gitlab/api/GitlabAPIT.java
getRawFileContent
getRawBlobContent
getFileArchive
getRepositoryTree
=> added methods:

.travis.yml, build.gradle, src/main/java/org/gitlab/api/GitlabAPI.java, src/test/java/org/gitlab/api/GitlabAPIT.java
This change fix command:
```
./gradlew build
```
It would also be reasonable to make an automatic compilation on the service like travis.
=> Compilation fix

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabSystemHook.java
https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/system_hooks.md
=> Add system hook API support

src/main/java/org/gitlab/api/GitlabAPI.java
The main changes is the use of the Query API instead of building the query string manually.
=> minor cosmetic cleanups

README.md
=> Maven badge

src/main/java/org/gitlab/api/GitlabAPI.java
This PR adds a method to retrieve the User utilizing the API.
=> Add method to return API User

src/main/java/org/gitlab/api/GitlabAPI.java
Implements the Update Merge Request API: http://doc.gitlab.com/ce/api/merge_requests.html#update-mr
=> Add Method to Update Merge Request

src/main/java/org/gitlab/api/GitlabAPI.java
Implements the following GitLab API Method: http://doc.gitlab.com/ce/api/notes.html#modify-existing-merge-request-note
=> Add Method to Update Merge Request Notes

src/main/java/org/gitlab/api/models/GitlabNote.java
Expose system, upvote and downvote flag of Gitlab Notes.
=> Add system, upvote, downvote to GitlabNote

src/main/java/org/gitlab/api/models/GitlabProject.java
Add missing fields to GitlabProject as defined here: http://doc.gitlab.com/ee/api/projects.html#get-single-project
=> Add missing fields to GitlabProject

src/main/java/org/gitlab/api/GitlabAPI.java
Implements Method to delete repository branch: http://doc.gitlab.com/ce/api/branches.html#delete-repository-branch
=> Add method to delete a branch

src/main/java/org/gitlab/api/GitlabAPI.java
Changed type to Number because it fits as well as Integer.
Added a descriptive IllegalArgumentException message.
=> Type checking and error message improved

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java
Now diffs of a big size can be handled with SocketTimeoutException.
=> Adds request timeout support.

src/main/java/org/gitlab/api/models/GitlabRelease.java, src/main/java/org/gitlab/api/models/GitlabTag.java
Hi!
I missed Tag functionality so I have implemented it.
Please let me know if anything could be improved.
Cheers.
=> Added Tag and Release models

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabBuild.java, src/main/java/org/gitlab/api/models/GitlabRunner.java
See the [API docs](http://doc.gitlab.com/ce/api/builds.html) for reference
=> Added builds API for projects and commits

src/main/java/org/gitlab/api/GitlabAPI.java
was having problem with a character '#' in a branch name
=> sanitize branches before calling api.

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabTag.java
implements api for get tags, add tag and delete tag
=> implements api for get tags, add tag and delete tag 

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabCommitComparison.java
See http://doc.gitlab.com/ce/api/repositories.html#compare-branches-tags-or-commits
=> Added ability to compare commits

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabProjectHook.java
Trying to solve Issue #132
based on official doc: http://doc.gitlab.com/ce/api/projects.html#add-project-hook
=> Added support for tag_push_events on project hooks

src/main/java/org/gitlab/api/models/GitlabProject.java
=> Project builds

src/main/java/org/gitlab/api/models/GitlabProjectAccessLevel.java
=> Fix: setNotificationLevel #140

src/main/java/org/gitlab/api/GitlabAPI.java
=> Added getNote(issue, noteId)

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabBuildVariable.java, src/test/java/org/gitlab/api/GitlabAPITest.java
Hi Tim,
I implemented CRUD operation for build variables, could you add to your project?
Viz http://docs.gitlab.com/ce/api/build_variables.html
=> Build variables implementation

src/main/java/org/gitlab/api/models/GitlabCommit.java
Changed the 'description' field to 'message' field. The 'description' field it was apparently deprecated.
=> Changed field deprecated

src/main/java/org/gitlab/api/models/GitlabBranch.java
https://docs.gitlab.com/ee/api/projects.html#list-branches
=> Remove trailing slash

src/main/java/org/gitlab/api/GitlabAPI.java
=> Get all members of group, not only the first page

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabEmailonPushProperties.java, src/main/java/org/gitlab/api/models/GitlabServiceEmailOnPush.java
Hi! Everyone,
I have added Email-on-Push and Search project.
Thanks,
Amudha Palani
=> Email-on-push and search project

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabRepositoryTree.java
See https://github.com/timols/java-gitlab-api/issues/183
=> Recursive file tree from repo

src/main/java/org/gitlab/api/models/GitlabRunner.java
The current model is missing some fields.
=> Add additional fields for Runner.

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java, src/main/java/org/gitlab/api/models/GitlabRunner.java
Make the User-Agent settable.
This makes it easier to see which program executed requests.
=> Modify user agent

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabCommit.java, src/main/java/org/gitlab/api/models/GitlabGroup.java, src/main/java/org/gitlab/api/models/GitlabMergeRequest.java, src/main/java/org/gitlab/api/models/GitlabRepositoryFile.java, src/main/java/org/gitlab/api/models/GitlabVersion.java
First of all, apologies for cramming many unrelated changes into one PR.
I'm working on [Jenkins gitlab integration](https://github.com/kohsuke/gitlab-branch-source-plugin) by using your library, and I had to add various API calls to the library.
Most changes are fairly straightforward. So I hope this change is acceptabe.
BTW, I'm the author of `github-api` library, and I smiled a little when I saw similarities in some parts of the library. Great minds think alike!
=> Various new API additions

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java
Add proxy support for `openConnection`
=> Add proxy support

src/main/java/org/gitlab/api/GitlabAPI.java
Addresses issue: Create Project for Group #196
=> Add the possibility of creating group projects

src/main/java/org/gitlab/api/GitlabAPI.java
Fix for issue: Add the possibility to create webhook with secret token #198
=> Add creating hooks with secret token.

src/main/java/org/gitlab/api/GitlabAPI.java
Hello,
According to the [api](https://docs.gitlab.com/ee/api/merge_requests.html#update-mr), the URL must be `.../merge_requests/` (the `s` was missing).
Best regards,
Cédric
=> fixes update/accept Merge Request URLs

src/main/java/org/gitlab/api/models/GitlabMergeRequest.java
Hello,
This simply add the property `mergeCommitSHA` and also the missing `@JSONProperty` on the `sha` field.
Best regards,
Cédric
=> Add missing field mergeCommitSHA and json property SHA

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabProject.java
This is intended to allow https://gitlab.com/gitlab-org/gitlab-ce/issues/32935 to be worked around, but maybe it will be more generally useful too.
=>  Add a createProject method that takes all the options

src/main/java/org/gitlab/api/models/GitlabCommit.java, src/main/java/org/gitlab/api/models/GitlabCommitStatus.java
Hello,
Adding hashcode,
2 equal object => same hashcode https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--
Best regards,
Emilien
=> add hashcode in GitlabCommit & GitlabCommitStatus

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabJiraProperties.java, src/main/java/org/gitlab/api/models/GitlabServiceJira.java
Added Jira Service
https://gitlab.com/help/api/services.md#jira
=> Add jira service

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/CreateUserRequest.java
New model-class and API-method added.
=> Custom createUser requests supported

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabProject.java
=> Add a project flag to the api

src/main/java/org/gitlab/api/models/GitlabProject.java
=> all properties need to be nullable

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabApprovedBy.java, src/main/java/org/gitlab/api/models/GitlabMergeRequestApprovals.java, src/main/java/org/gitlab/api/models/GitlabUser.java
I think this is an EE feature.
=> merge request approvals

src/main/java/org/gitlab/api/models/GitlabUser.java
add the LastActivityOn field in GitlabUser.
https://docs.gitlab.com/ce/api/users.html
=> add LastActivityOn field in GitlabUser

src/main/java/org/gitlab/api/GitlabAPI.java
This PR upgrade file create/update/delete actions to API v4
=> Repository file create update v4

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabNamespace.java, src/main/java/org/gitlab/api/models/GitlabProject.java, src/test/java/org/gitlab/api/GitlabAPIIT.java
- Add a method getNamespace 
- fix URL for Namespace
- create a fork
- add forkedfrom field in project
- add tests
- Use url of Group instead of url of Namespace for transfert, and getNamespaceMembers (A better name would be getGroupMembers)
=> fix namespace, add create a fork, add forkedfrom field in project ,add tests

src/main/java/org/gitlab/api/models/GitlabUser.java
See https://github.com/timols/java-gitlab-api/pull/236#discussion_r141539662
=> make blocked nullable

.gitignore, build.gradle, pom.xml, src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabRunner.java, src/main/java/org/gitlab/api/models/GitlabUser.java
- Expose Runner Status API
- Update `build.gradle`
- Updated to latest snapshot version presented in `pom.xml`
- Use latest patch version of `jackson` library
- Updated to latest Gradle plugins syntax
- Updated Gradle Wrapper to `4.4`
- Added more generated files/directories to `.gitignore`
- Updated `pom.xml` 
- Updated to version `0.23.0` of `fabric8`'s maven plugin to run integration test locally
- Updated source/target compatibility to Java8
- Addressed potential bug of returning nullable `Boolean` as primitive `boolean`.
=> Runner Status

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabCommit.java, src/main/java/org/gitlab/api/models/GitlabPipeline.java
I added the job API from Gitlab to get pipelines per pipeline and play, cancel and retry jobs.
see [on Gitlab](https://docs.gitlab.com/ee/api/jobs.html)
=> Introduced Job API

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabGroup.java, src/main/java/org/gitlab/api/models/GitlabUser.java, src/test/java/org/gitlab/api/GitlabAPIIT.java
Changes:
-  Add attribute "external" to GitlabUser
- Add missing attributes to GitabGroup
=> Add some properties to GitlabUser and GitlabGroup

src/main/java/org/gitlab/api/models/GitlabIssue.java
=> 295 missing attributes in gitlab issue class

CHANGES.txt, build.gradle, pom.xml, src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java, src/main/java/org/gitlab/api/http/Method.java, src/test/java/org/gitlab/api/GitlabAPIIT.java, src/test/java/org/gitlab/api/GitlabAPIUT.java, src/test/java/org/gitlab/api/http/GitlabHTTPRequestorTest.java, src/test/resources/log4j2.xml
Refactoring: add getter for host field GitlabAPI &&
remove unused IOException from the method signature
=> Fixed: GITHUB-297: The "connectTimeout" parameter is not configurable

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java, src/main/java/org/gitlab/api/models/GitlabProject.java
=> Fixed pagination parameter and project parameter name

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabBadge.java
In keeping with [project](https://docs.gitlab.com/ee/api/project_badges.html) and  [group](http s://docs.gitlab.com/ee/api/group_badges.html)  level badge operations.
=> Add badge support

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabProjectHook.java
- Adding new attributes on GitlabProjectHook
- Adding new signature on addProjectHook method
- Adding new signature on editProjectHook method
=> Improvements on GitlabProjectHook

src/main/java/org/gitlab/api/models/GitlabTag.java
=> Change type of GitlabTag commit property to GitlabCommit.

src/main/java/org/gitlab/api/GitlabAPI.java, src/main/java/org/gitlab/api/models/GitlabBuildVariable.java, src/main/java/org/gitlab/api/models/GitlabPipeline.java
(similar to web interface's Pipelines -> Run Pipeline)
=> Added ability to run pipelines

src/main/java/org/gitlab/api/GitlabAPI.java
This is a major perf win with lots of projects
=> allow fetching groups w/o projects
